### ISSUE TITLE
Does not work with cdk@1.19.0

### ISSUE THREAD

**Issue by mteichtahl** [cdklabs/aws-delivlib#205]
Seems like these is a compatibility issue with dependencies between this package and cdk@1.19.0

is there a plan to close track the latest CDK version ?

```
➜  cdkDevPipeline git:(master) ✗ cdk --version
1.19.0 (build 5597bbe)
```

package.json
```json
{
  "name": "cdk_dev_pipeline",
  "version": "0.1.0",
  "bin": {
    "cdk_dev_pipeline": "bin/cdk_dev_pipeline.js"
  },
  "scripts": {
    "build": "tsc",
    "watch": "tsc -w",
    "test": "jest",
    "cdk": "cdk"
  },
  "devDependencies": {
    "@aws-cdk/assert": "^1.19.0",
    "@types/jest": "^24.0.22",
    "@types/node": "10.17.5",
    "jest": "^24.9.0",
    "ts-jest": "^24.1.0",
    "aws-cdk": "^1.15.0",
    "ts-node": "^8.1.0",
    "typescript": "~3.7.2"
  },
  "dependencies": {
    "@aws-cdk/aws-codecommit": "^1.15.0",
    "@aws-cdk/core": "^1.15.0",
    "aws-delivlib": "^4.5.1",
    "source-map-support": "^0.5.16"
  }
}
```

Errors
```
  cdkDevPipeline git:(master) ✗ npm run build    

> cdk_dev_pipeline@0.1.0 build /Volumes/workplace/playground/cdkDevPipeline
> tsc

test/cdk_dev_pipeline.test.ts:10:15 - error TS2345: Argument of type 'CdkDevPipelineStack' is not assignable to parameter of type 'CloudFormationStackArtifact | Stack'.
  Type 'CdkDevPipelineStack' is missing the following properties from type 'Stack': artifactId, nestedStackParent, addTransform, generateUniqueId

10     expectCDK(stack).to(matchTemplate({
                 ~~~~~


Found 1 error.

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! cdk_dev_pipeline@0.1.0 build: `tsc`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the cdk_dev_pipeline@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/teichtah/.npm/_logs/2019-12-20T03_20_37_709Z-debug.log
```

**Comment by skinny85** [comment]
Hi @mteichtahl ,

we actually already did the brunt of the work to migrate to 1.19.0 in #184 . Right now, we're waiting with the next release until we migrate the custom resource Lambdas to a Node10 runtime (as the Node8 runtime used currently is no longer supported by Lambda), which is done in #226 . After that is merged, we will release a new version that's compatible with 1.19.0.

Thanks,
Adam

**Comment by ahammond** [comment]
This looks obsolete since... I'm currently running it using cdk 1.19.0.
